# Generated by Django 2.2.4 on 2020-05-15 06:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('APN', models.CharField(default='000-000-0000', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('school_district', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('SFH', 'SFH'), ('DUP', 'Duplex'), ('APT', 'Apartment'), ('CND', 'Condo'), ('MBH', 'Mobile Home'), ('CMR', 'Commercial Retail'), ('CMO', 'Commercial Office'), ('CMW', 'Commercial Warehouse'), ('CML', 'Commercial W/O Lot')], default='SFH', max_length=3)),
                ('status', models.CharField(choices=[('1', 'Rented'), ('2', 'Available'), ('3', 'For Sale'), ('4', 'Under Construction'), ('5', 'Owner Occupied')], default='2', max_length=1)),
                ('ac', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=2, max_length=3)),
                ('heating', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=2, max_length=3)),
                ('water_heater', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=2, max_length=3)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('stories', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('parking', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=2, max_length=3)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('year_built', models.CharField(default='1900', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('roof_type', models.CharField(choices=[('1', 'Asphalt'), ('2', 'Clay/Concrete'), ('3', 'Slate'), ('4', 'Metal'), ('5', 'Wood')], default='1', max_length=1)),
                ('roof_year', models.CharField(default='1900', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('purchase_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('purchase_escrow_agent', models.CharField(blank=True, max_length=200)),
                ('purchase_escrow_number', models.CharField(blank=True, max_length=200)),
                ('sold_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sold_amt', models.IntegerField()),
                ('sale_escrow_agent', models.CharField(blank=True, max_length=200)),
                ('sale_escrow_number', models.CharField(blank=True, max_length=200)),
                ('pct_ownership', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('assessed_value', models.IntegerField()),
                ('property_tax', models.IntegerField()),
                ('property_tax_county', models.CharField(blank=True, max_length=200)),
                ('current_value', models.IntegerField()),
                ('owned_equity', models.IntegerField()),
                ('partner', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_manager', to='managers.Manager')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_status', models.CharField(choices=[('1', 'Rented'), ('2', 'Available'), ('3', 'Available Soon'), ('4', 'Under Repair')], default='2', max_length=1)),
                ('lease_number', models.CharField(max_length=200)),
                ('rental_price', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
                ('other_fees', models.IntegerField()),
                ('lease_start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lease_end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rental_notes', models.TextField(blank=True)),
                ('tenant_name', models.CharField(blank=True, max_length=50)),
                ('tenant_phone', models.CharField(blank=True, max_length=10)),
                ('tenant_phone2', models.CharField(blank=True, max_length=10)),
                ('tenant_email', models.CharField(blank=True, max_length=50)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rental', to='listings.Listing')),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, max_length=200)),
                ('lender', models.CharField(blank=True, max_length=200)),
                ('monthly_pmt', models.IntegerField(default=0)),
                ('mortgage_total', models.IntegerField(default=0)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('impound', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mortgage', to='listings.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('repair_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cost', models.IntegerField(default=0)),
                ('repair_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default=1, max_length=10)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('maintenance_notes', models.TextField()),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenance', to='listings.Listing')),
            ],
            options={
                'verbose_name': 'Maintenance Job',
                'verbose_name_plural': 'Maintenance Jobs',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=200)),
                ('liability_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('replacement_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('effective_start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('effective_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('monthly_pmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('insurance_notes', models.TextField(blank=True)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance', to='listings.Listing')),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('1', 'Electric'), ('2', 'Gas'), ('3', 'Water'), ('4', 'Garbage'), ('5', 'HOA'), ('6', 'Other')], default='6', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.IntegerField()),
                ('recurrence', models.CharField(choices=[('1', 'Monthly'), ('2', 'Annually'), ('3', 'Quarterly'), ('4', 'One-Time'), ('5', 'Other')], default='1', max_length=20)),
                ('autopay', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='1', max_length=20)),
                ('expense_notes', models.TextField(blank=True)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense', to='listings.Listing')),
            ],
        ),
    ]
