# Generated by Django 2.2.4 on 2020-05-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200514_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance Job', 'verbose_name_plural': 'Maintenance Jobs'},
        ),
    ]
