# Generated by Django 2.2.4 on 2020-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200514_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Insurance Policy', 'verbose_name_plural': 'Insurance Policies'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Lease', 'verbose_name_plural': 'Leases'},
        ),
    ]
