# Generated by Django 2.2.4 on 2020-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200514_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='asking_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='target_rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
