# Generated by Django 2.2.4 on 2020-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200514_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='repair_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default=1, max_length=10),
        ),
    ]
