# Generated by Django 2.2.4 on 2020-05-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200514_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance', to='listings.Listing'),
        ),
    ]
