# Generated by Django 2.2.4 on 2020-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200514_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='assessed_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owned_equity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
