# Generated by Django 2.2.4 on 2020-05-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200514_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('1', 'Electric'), ('2', 'Gas'), ('3', 'Water'), ('4', 'Garbage'), ('5', 'HOA'), ('6', 'Other')], default='6', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.IntegerField()),
                ('recurrence', models.CharField(choices=[('1', 'Monthly'), ('2', 'Annually'), ('3', 'Quarterly'), ('4', 'One-Time'), ('5', 'Other')], default='1', max_length=20)),
                ('autopay', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='1', max_length=20)),
                ('expense_notes', models.TextField(blank=True)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense', to='listings.Listing')),
            ],
        ),
    ]
