# Generated by Django 2.2.4 on 2020-05-14 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, max_length=200)),
                ('lender', models.CharField(blank=True, max_length=200)),
                ('monthly_pmt', models.IntegerField(default=0)),
                ('mortgage_total', models.IntegerField(default=0)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('impound', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mortgage', to='listings.Listing')),
            ],
        ),
    ]
