# Generated by Django 2.2.4 on 2020-05-15 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_mortgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='effective_date',
            new_name='effective_end_date',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='coverage_amt',
            new_name='liability_amt',
        ),
        migrations.AddField(
            model_name='insurance',
            name='effective_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='insurance',
            name='replacement_amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='partner',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='property_tax_county',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='purchase_escrow_agent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='purchase_escrow_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_escrow_agent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_escrow_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rental',
            name='lease_number',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
