# Generated by Django 2.2.4 on 2020-05-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200515_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='mortgage_total',
        ),
        migrations.AddField(
            model_name='expense',
            name='responsibility',
            field=models.CharField(choices=[('1', 'Owner Pays'), ('2', 'Tenant Pays')], default='1', max_length=7),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('1', 'Electric'), ('2', 'Gas'), ('3', 'Water'), ('4', 'Garbage'), ('5', 'HOA'), ('5', 'Sewer'), ('6', 'Other')], default='6', max_length=20),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='monthly_pmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
