# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-08 11:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('apn', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('neighborhood', models.CharField(max_length=200)),
                ('school_district', models.CharField(max_length=200)),
                ('bedrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1)),
                ('garage', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3)),
                ('stories', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1)),
                ('parking', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3)),
                ('year_built', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('roof_type', models.CharField(choices=[('1', 'Asphalt'), ('2', 'Clay/Concrete'), ('3', 'Slate'), ('4', 'Metal'), ('5', 'Wood')], default='1', max_length=1)),
                ('roof_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('heating', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3)),
                ('ac', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3)),
                ('water_heater', models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3)),
                ('type', models.CharField(choices=[('SFH', 'SFH'), ('DUP', 'Duplex'), ('APT', 'Apartment'), ('CND', 'Condo'), ('MBH', 'Mobile Home'), ('CMR', 'Commercial Retail'), ('CMO', 'Commercial Office'), ('CMW', 'Commercial Warehouse'), ('CML', 'Commercial W/O Lot')], default='SFH', max_length=3)),
                ('status', models.CharField(choices=[('1', 'Rented'), ('2', 'Available'), ('3', 'For Sale'), ('4', 'Under Construction'), ('5', 'Owner Occupied')], default='2', max_length=1)),
                ('notes', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
