# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-08 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='roof_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='roof_year',
        ),
        migrations.RemoveField(
            model_name='property',
            name='stories',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_heater',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
    ]
