# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-08 11:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200508_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ac',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='roof_type',
            field=models.CharField(choices=[('1', 'Asphalt'), ('2', 'Clay/Concrete'), ('3', 'Slate'), ('4', 'Metal'), ('5', 'Wood')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='property',
            name='roof_year',
            field=models.CharField(default='1900', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='stories',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='property',
            name='water_heater',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.CharField(default='1900', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
