# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-08 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200508_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 8, 6, 54, 243882, tzinfo=utc)),
        ),
    ]
