# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-08 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200508_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
