# Generated by Django 2.2.4 on 2020-05-15 06:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200514_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='size',
        ),
        migrations.AddField(
            model_name='listing',
            name='percent_ownership',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sold_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
