# Generated by Django 2.2.4 on 2020-05-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200515_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lease_contract',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
