# Generated by Django 2.2.4 on 2020-05-17 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_rental_lease_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='lease_contract',
            new_name='lease_agreement',
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_end',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_start',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
