# Generated by Django 2.2.4 on 2020-05-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20200516_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_document',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_policy',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='mortgage_documents',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
