# Generated by Django 2.2.4 on 2020-05-17 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200516_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='effective_end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='effective_start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
