# Generated by Django 2.2.4 on 2020-05-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20200516_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_document',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
