# Generated by Django 2.2.4 on 2020-05-17 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_maintenance_maintenance_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='repair_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
