# Generated by Django 2.2.4 on 2020-05-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20200516_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='purchase_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
