# Generated by Django 2.2.4 on 2020-05-20 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20200517_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
