# Generated by Django 2.2.4 on 2020-07-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20200520_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='annual_pmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
