# Generated by Django 2.2.4 on 2020-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_expense_annual_pmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('1', 'Electric'), ('2', 'Gas'), ('3', 'Water'), ('4', 'Garbage'), ('5', 'HOA'), ('6', 'Sewer'), ('7', 'Other')], default='6', max_length=20),
        ),
    ]
