# Generated by Django 2.2.4 on 2020-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20200716_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Gas', 'Gas'), ('Water', 'Water'), ('Garbage', 'Garbage'), ('HOA', 'HOA'), ('Sewer', 'Sewer'), ('Other', 'Other')], default='6', max_length=20),
        ),
    ]
