# Generated by Django 2.2.4 on 2020-08-18 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20200716_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_document', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document', to='listings.Listing')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
