# Generated by Django 2.2.4 on 2020-08-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='expense_document',
            new_name='document',
        ),
    ]
