# Generated by Django 2.2.4 on 2020-08-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20200817_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
