# Generated by Django 2.2.4 on 2020-08-18 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20200817_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document1', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('document2', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('document3', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('document4', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('document5', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acquisition_disposition', to='listings.Listing')),
            ],
            options={
                'verbose_name': 'Acquisition Disposition',
                'verbose_name_plural': 'Acquisition Disposition',
            },
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
