# Generated by Django 2.2.4 on 2020-08-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20200817_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='asking_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='sales_price',
            field=models.IntegerField(blank=True, default=10000000),
            preserve_default=False,
        ),
    ]
