# Generated by Django 2.2.4 on 2020-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20200817_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sales_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='target_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
