# Generated by Django 2.2.4 on 2020-08-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_auto_20200817_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Property', 'verbose_name_plural': '1. Properties'},
        ),
    ]
