# Generated by Django 2.2.4 on 2020-08-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_auto_20200817_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitiondisposition',
            options={'verbose_name': 'Acquisition Disposition', 'verbose_name_plural': '6. Acquisition Disposition'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': '4. Expenses'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Insurance Policy', 'verbose_name_plural': '3. Insurance Policies'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance Job', 'verbose_name_plural': '5. Maintenance Jobs'},
        ),
        migrations.AlterModelOptions(
            name='mortgage',
            options={'verbose_name': 'Mortgage', 'verbose_name_plural': '7. Mortgages'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Lease', 'verbose_name_plural': '2. Leases'},
        ),
    ]
